# -*- coding: utf-8 -*-
"""New Web Scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5XY7IM1QlGiBe4_e-XSInsQu1E_JAwH
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_table(url):
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
    soup = BeautifulSoup(response.text, "html.parser")

    table = soup.find("table", {"class": "wikitable"})
    if table is None:
        raise Exception(f"No table found at {url}")

    # Headers
    headers = [th.text.strip() for th in table.find_all("th")]

    # Rows
    rows = []
    for tr in table.find_all("tr")[1:]:
        cells = [td.text.strip() for td in tr.find_all("td")]
        if cells:
            rows.append(cells)

    df = pd.DataFrame(rows, columns=headers[:len(rows[0])])
    return df

# URLs
url_nominal = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
url_growth = "https://en.wikipedia.org/wiki/List_of_countries_by_real_GDP_growth_rate"



df_nominal = scrape_table(url_nominal)
df_growth = scrape_table(url_growth)


#for
with pd.ExcelWriter("gdp_data.xlsx") as writer:
    df_nominal.to_excel(writer, sheet_name="GDP_Nominal", index=False)
    df_growth.to_excel(writer, sheet_name="GDP_Growth", index=False)

print("Nominal Rows:", len(df_nominal))
print("Growth Rows:", len(df_growth))
print("Saved to gdp_data.xlsx with 2 sheets!")



